# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/jasondel-test-project/frontend
    context: src/frontend
  - image: gcr.io/jasondel-test-project/ledgerwriter
    jib:
      project: src/ledgerwriter
  - image: gcr.io/jasondel-test-project/balancereader
    jib:
      project: src/balancereader
  - image: gcr.io/jasondel-test-project/transactionhistory
    jib:
      project: src/transactionhistory
  - image: gcr.io/jasondel-test-project/contacts
    context: src/contacts
  - image: gcr.io/jasondel-test-project/userservice
    context: src/userservice
  - image: gcr.io/jasondel-test-project/loadgenerator
    context: src/loadgenerator
  - image: gcr.io/jasondel-test-project/accounts-db
    context: src/accounts-db
  - image: gcr.io/jasondel-test-project/ledger-db
    context: src/ledger-db
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
    - ./dev-kubernetes-manifests/**.yaml
    # deploy a pre-build secret
    # in practice, this should not be checked in to source control
    - ./extras/jwt/jwt-secret.yaml
profiles:
  - name: local-code
